import os
CSRF_ENABLED = True
SECRET_KEY = '**SECRET_KEY**'
JSON_SORT_KEYS = False

basedir = os.path.abspath(os.path.dirname(__file__))

SQLALCHEMY_DATABASE_URI = 'mysql://**USER**:*PASSWORD**@**HOST**/**DB**'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQL_ALCHEMY_POOL_RECYCLE = 50
SQLALCHEMY_POOL_SIZE = 100
SQLALCHEMY_ENGINE_OPTIONS = {'pool_size' : 100, 'pool_recycle' : 50, 'pool_pre_ping': True}

REMEMBER_COOKIE_SECURE = True
REMEMBER_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
REMEMBER_COOKIE_REFRESH_EACH_REQUEST = True
SESSION_PROTECTION = "basic"
MAX_CONTENT_LENGTH = 50 * 1024 * 1024
DIR_PATH = os.path.dirname(os.path.realpath(__file__))
AVATARS_SAVE_PATH = DIR_PATH + "/app/static/avatars"
AVATARS_SIZE_TUPLE = [30, 90, 180]
AVATARS_CROP_INIT_SIZE = 180
ALLOWED_FILE_EXTENSIONS = ['png', 'jpg', 'jpeg']
