"""user->log fkey

Revision ID: 49b10f4c0509
Revises: f84d160961de
Create Date: 2021-12-02 08:39:22.345916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b10f4c0509'
down_revision = 'f84d160961de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'money_log', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'money_log', type_='foreignkey')
    # ### end Alembic commands ###
