"""

Revision ID: 52441b65f520
Revises: 82a52a67209f
Create Date: 2021-09-17 16:39:34.846239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52441b65f520'
down_revision = '82a52a67209f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('money_log', 'timestamp',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('money_log', 'timestamp',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
