"""currency add

Revision ID: 63e6c57e5c14
Revises: 0ad12313233f
Create Date: 2021-09-23 19:14:55.213424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e6c57e5c14'
down_revision = '0ad12313233f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('currency', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'currency')
    # ### end Alembic commands ###
