"""nickname -> username

Revision ID: 6e73de9c3723
Revises: 0d02eab93c0c
Create Date: 2021-09-14 20:17:25.400436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e73de9c3723'
down_revision = '0d02eab93c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.drop_index('ix_user_nickname', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True))
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=False)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
