"""datetime -> date

Revision ID: 899d4b542e10
Revises: 6e73de9c3723
Create Date: 2021-09-16 19:50:08.479349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '899d4b542e10'
down_revision = '6e73de9c3723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=False)
    op.alter_column('money_log', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=True)
    op.alter_column('money_log', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               nullable=True)
    op.alter_column('group', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=True)
    # ### end Alembic commands ###
