"""registered date

Revision ID: c621ff3d3dbb
Revises: 1d114718ba01
Create Date: 2021-09-22 19:26:12.814805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c621ff3d3dbb'
down_revision = '1d114718ba01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registered', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registered')
    # ### end Alembic commands ###
