"""group->monelog fkey

Revision ID: ddff206198e7
Revises: 49b10f4c0509
Create Date: 2021-12-02 09:00:17.134148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddff206198e7'
down_revision = '49b10f4c0509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'money_log', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'money_log', type_='foreignkey')
    # ### end Alembic commands ###
