"""role del

Revision ID: f84d160961de
Revises: 63e6c57e5c14
Create Date: 2021-10-11 21:33:39.046122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f84d160961de'
down_revision = '63e6c57e5c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
